// You can find instructions for this file here:
// http://www.treeview.net

// Decide if the names are links or just the icons
USETEXTLINKS = 1  //replace 0 with 1 for hyperlinks

// Decide if the tree is to start all open or just showing the root folders
STARTALLOPEN = 0 //replace 0 with 1 to show the whole tree

ICONPATH = '' //change if the gif's folder is a subfolder, for example: 'images/'
USEICONS = 0


foldersTree = gFld("<font size=2> Book of the Month</font>")
  aux1 = insFld(foldersTree, gFld("2002", "right.html"))
    aux2 = insFld(aux1, gFld("September - Scared Cactus",
"javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2002/sep/image.html"))
      insDoc(aux2, gLnk("R", "Smilla's Sense of Snow", "2002/sep/expl.html"))
    aux2 = insFld(aux1, gFld("October - Cactus", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2002/oct/image.html"))
      insDoc(aux2, gLnk("R", "Alligators", "2002/oct/expl.html"))      
    aux2 = insFld(aux1, gFld("November - Mitochondria", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2002/nov/image.html"))
      insDoc(aux2, gLnk("R", "Biology", "2002/nov/expl.html"))      
    aux2 = insFld(aux1, gFld("December - Peace", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2002/dec/image.html"))
      insDoc(aux2, gLnk("R", "Birds", "2002/dec/expl.html"))
      
  aux1 = insFld(foldersTree, gFld("2003", "right.html"))
    aux2 = insFld(aux1, gFld("January - Little Clouds", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/jan/image.html"))
      insDoc(aux2, gLnk("R", "Dieter Roth", "2003/jan/expl.html"))
    aux2 = insFld(aux1, gFld("February - Demons", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/feb/image.html"))
      insDoc(aux2, gLnk("R", "Gabberbochus Press", "2003/feb/expl.html"))
    aux2 = insFld(aux1, gFld("March - NOISE", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/mar/image.html"))
      insDoc(aux2, gLnk("R", "Envelopes", "2003/mar/expl.html"))
    aux2 = insFld(aux1, gFld("April - Pure Gobi", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/apr/image.html"))
      insDoc(aux2, gLnk("R", "John McPhee", "2003/apr/expl.html"))
    aux2 = insFld(aux1, gFld("May - more, better", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/may/image.html"))
      insDoc(aux2, gLnk("R", "Mathematica", "2003/may/expl.html"))
    aux2 = insFld(aux1, gFld("June - mango", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/jun/image.html"))
      insDoc(aux2, gLnk("R", "Time", "2003/jun/expl.html"))
    aux2 = insFld(aux1, gFld("July - mmmmmm", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/jul/image.html"))
      insDoc(aux2, gLnk("R", "Bookbinding", "2003/jul/expl.html"))
    aux2 = insFld(aux1, gFld("August - plants/overpass", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/aug/image.html"))
      insDoc(aux2, gLnk("R", "Freeways", "2003/aug/expl.html"))
    aux2 = insFld(aux1, gFld("September - Chicken", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/sep/image.html"))
      insDoc(aux2, gLnk("R", "Unica T", "2003/sep/expl.html"))
    aux2 = insFld(aux1, gFld("October - Hurry", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/oct/image.html"))
      insDoc(aux2, gLnk("R", "Alduous Huxley", "2003/oct/expl.html"))
    aux2 = insFld(aux1, gFld("November - Mango, Pt. 2", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/nov/image.html"))
      insDoc(aux2, gLnk("R", "Watercolors", "2003/nov/expl.html"))
    aux2 = insFld(aux1, gFld("December - Peace", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2003/dec/image.html"))
      insDoc(aux2, gLnk("R", "Pop-ups", "2003/dec/expl.html"))

  aux1 = insFld(foldersTree, gFld("2004", "right.html"))
    aux2 = insFld(aux1, gFld("January - MIGHT", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/jan/image.html"))
      insDoc(aux2, gLnk("R", "Paper", "2004/jan/expl.html"))
    aux2 = insFld(aux1, gFld("February - no!", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/feb/image.html"))
      insDoc(aux2, gLnk("R", "Jimmy Corrigan", "2004/feb/expl.html"))
    aux2 = insFld(aux1, gFld("March - DCMARCH2004", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/mar/image.html"))
      insDoc(aux2, gLnk("R", "John Barth", "2004/mar/expl.html"))
    aux2 = insFld(aux1, gFld("April - Guardian Thug", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/apr/image.html"))
      insDoc(aux2, gLnk("R", "Guardian Angel", "2004/apr/expl.html"))
    aux2 = insFld(aux1, gFld("May - Garden Slug", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/may/image.html"))
      insDoc(aux2, gLnk("R", "Guardian Thug", "2004/may/expl.html"))
    aux2 = insFld(aux1, gFld("June - Failure", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/jun/image.html"))
      insDoc(aux2, gLnk("R", "Russian Avant-Garde", "2004/jun/expl.html"))
    aux2 = insFld(aux1, gFld("July - vrroom", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/jul/image.html"))
      insDoc(aux2, gLnk("R", "Challenges", "2004/jul/expl.html"))
    aux2 = insFld(aux1, gFld("August - All of My Friends Are Flakes", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/aug/image.html"))
      insDoc(aux2, gLnk("R", "Flakes", "2004/aug/expl.html"))
    aux2 = insFld(aux1, gFld("September, Part One - Dinner", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/megan/image.html"))
      insDoc(aux2, gLnk("R", "Food", "2004/megan/expl.html"))
    aux2 = insFld(aux1, gFld("September, Part Two - HOR SES", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/sep/image.html"))
      insDoc(aux2, gLnk("R", "Exquisite Horse", "2004/sep/expl.html"))
      insDoc(aux2, gLnk("R", "PDF Files", "2004/sep/files.html"))
    aux2 = insFld(aux1, gFld("October - Lines", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/oct/image.html"))
      insDoc(aux2, gLnk("R", "Stories", "2004/oct/expl.html"))
    aux2 = insFld(aux1, gFld("November - Transit", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/nov/image.html"))
      insDoc(aux2, gLnk("R", "Scavenger Hunt", "2004/nov/expl.html"))
    aux2 = insFld(aux1, gFld("December - Peace", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2004/dec/image.html"))
      insDoc(aux2, gLnk("R", "Hate Dove", "2004/dec/expl.html"))

  aux1 = insFld(foldersTree, gFld("2005", "right.html"))
    aux2 = insFld(aux1, gFld("January - Vi Voodoo Card", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2005/jan/image.html"))
      insDoc(aux2, gLnk("R", "Resolutions", "2005/jan/expl.html"))
    aux2 = insFld(aux1, gFld("February - Bunny Rabbits Help Vi Work", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2005/feb/image.html"))
      insDoc(aux2, gLnk("R", "Songmaking", "2005/feb/expl.html"))
    aux2 = insFld(aux1, gFld("March - white box", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2005/mar/image.html"))
      insDoc(aux2, gLnk("R", "Buddha", "2005/mar/expl.html"))
    aux2 = insFld(aux1, gFld("April - Thief", "javascript:parent.op()"))
      insDoc(aux2, gLnk("R", "Images", "2005/apr/image.html"))
      insDoc(aux2, gLnk("R", "Palindrome", "2005/apr/expl.html"))

